version: '3'

services:
  db:
    image: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: c21u_admin_cert_access
        POSTGRES_DB: certs
  web:
    build: ..
    command: sh /code/run.sh
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_HOST: db
      DB_USER: admin
      DB_NAME: certs
      DB_PASSWORD: c21u_admin_cert_access
      DEBUG: "True"
      MANDRILL_API_KEY: $MANDRILL_API_KEY
      SENDGRID_API_KEY: $SENDGRID_API_KEY
      HOSTNAME: web
      VIRTUAL_HOST: admin.127.0.0.1.xip.io
      CAS_SERVER_URL: https://casserver.herokuapp.com/cas/
    volumes:
      - ..:/code
    expose:
      - "8000"
    depends_on:
      - db

  e2e:
    container_name: cypress
    build: .
    depends_on:
      - web
    command: npx cypress run
    environment:
      CYPRESS_baseUrl: http://web:8000
    volumes:
      - ./cypress:/app/cypress:rw
      - ./cypress.json:/app/cypress.json:ro
      - ./cypress.env.json:/app/cypress.env.json:ro
    
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $HOME/certs:/etc/nginx/certs

volumes:
  postgres_data:
